on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

name: "Deploy"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 6.23.6
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: pnpm

      - run: pnpm install
      - run: pnpm build

      - run: pnpm prepare-deploy
      - uses: ngduc/vercel-deploy-action@master
        with:
          vercel-cli: vercel
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # vercel-args: "--prod" #Optional
          working-directory: packages/vscode-host/dist
